# settings.yml

repository:
  
  name: workflow-testing
  
  private: false
  
  default_branch: master
  
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

branches:
  
  - name: master
    
    protection:
      
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      
      required_status_checks:
        strict: true
      
      enforce_admins: true
      
      restrictions:
        apps: []
        users: []
        teams: []
